# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20171130_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tests',
            field=models.ManyToManyField(blank=True, to='students.Exams', verbose_name='\u0406\u0441\u043f\u043c\u0442\u043c'),
        ),
    ]
