# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20171130_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tests',
        ),
    ]
