# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_group_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='groups',
        ),
        migrations.AddField(
            model_name='exams',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='\u0413\u0440\u0443\u043f\u0430'),
        ),
    ]
