# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20180106_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthjournal',
            name='present_day',
            field=models.BooleanField(default=False),
        ),
    ]
