# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_monthjournal_present_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthjournal',
            old_name='present_day',
            new_name='i',
        ),
    ]
